# Generated by Django 5.1 on 2024-09-17 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingu1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
